### ISSUE TITLE
Unit tests with zuul

### ISSUE THREAD

**Issue by adriengibrat** [treojs/idb-request#1]
Hello,

Follow up of alekseykulikov/treo#27 issue.

I've made a test adriengibrat/idb-request@d19cd9d3fb with [es6-promise](https://github.com/jakearchibald/es6-promise) and [zuul](https://github.com/defunctzombie/zuul).

The situation with tests:

> - [x] pass in Chrome
> - [x] pass in Firefox
> - [x] don't run in Safari at all

I hope using the shim will make it work...

> - [x] don't run in Phantomjs 1.9 with indexeddb-shim

it seems the shim is not working in Phantomjs

**Comment by alekseykulikov** [comment]
Hello,

Thank you for investigation of this issue. If es6-promise works, it's great, because it's quite small and well supported. In docs, we can just recommend it or bluebird.

> it seems the shim is not working in Phantomjs

It works, check out https://travis-ci.org/alekseykulikov/treo. It's a full-featured treo's test-suite running in Phantomjs 1.9. Also it works in Safari. Need to figure out why idb-request fails, might be issues with `onversionchange` event.

**Comment by alekseykulikov** [comment]
@adriengibrat I was able to pass tests in Safari. There were 3 issues:
- it does not support e.oldVersion properly
- it does not handle `onversionchange` right and can't close db immediately
- it does not support transactions to group of stores

And yes, es6-promise works great!

**Comment by adriengibrat** [comment]
Nice,

So if i got it right:
- current shim should address onversionchange / e.oldVersion + transaction
  issues, if used instead of Safari buggy implementation.
-  shim should be improved to handle onversionchange event on Phantomjs

FYI, other Promise implementations I've tested (Promiz
https://github.com/zolmeister/promiz, then/promise
https://github.com/then/promise, vow
https://github.com/dfilatov/jspromise) failed tests using Promise.all.

Adrien

2015-04-02 12:58 GMT+02:00 Aleksey Kulikov notifications@github.com:

**Comment by alekseykulikov** [comment]
Well, it wasn't easy, but I passed tests in PhantomJS env using Websql-shim. 

> So if i got it right:

Actually not, it does not address non of this problems, and sometimes makes things even worse. 
That's why I decided to rewrite it here: https://github.com/treojs/idb-polyfill, but it's WIP and not related with this library.

I think, now we have test-suite that passes in all available environment.
Could you make a pull-request with your zuul integration code? Also I would like to have this cool browsers support badge.

**Comment by adriengibrat** [comment]
will do tonight ;)

Adrien

2015-04-02 14:03 GMT+02:00 Aleksey Kulikov notifications@github.com:

**Comment by alekseykulikov** [comment]
Perfect, thanks!
